Repository NaomiProject/Naomi, pull requests merged in 2018-12, with the labels that each got.

#115 mpdclient: Do not set an unexisting password
  plugins/speechhandler/mpdcontrol/mpdclient.py
Labels: bug

#123 Fix issue where dictionary is lower case
  plugins/stt/pocketsphinx-stt/g2p.py
  plugins/stt/pocketsphinx-stt/sphinxvocab.py
Labels: Status: Completed, Type: Bug

#122 Adjusting setup script & python requirements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  AUTHORS.md
  README.md
  naomi-setup.sh
  python_requirements.txt
Labels: CLA: Signed, Status: Completed, Type: Maintenance

#134 Readme Update - Master
  README.md
Labels: CLA: Signed, Priority: Low, Status: Completed, Type: Maintenance

#138 naomi-setup.sh fixes to Naomi-Dev
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  naomi-setup.sh
  naomi/populate.py
  plugins/stt/pocketsphinx-stt/sphinxvocab.py
  python_requirements.txt
Labels: CLA: Signed, Priority: High, Status: Completed, Type: Bug

#137 Fixed a few issues with Naomi 2.2
  .gitignore
  naomi-setup.sh
  naomi/populate.py
  plugins/stt/pocketsphinx-stt/sphinxvocab.py
  python_requirements.txt
Labels: CLA: Signed, Priority: High, Status: Completed, Type: Bug

#135 Readme Update - Dev
  README.md
Labels: CLA: Signed, Priority: Low, Status: Completed, Type: Maintenance
