Repository NaomiProject/Naomi, pull requests merged in 2019-01, with the labels that each got.

#142 Add Audio Transcript
  naomi/__main__.py
  naomi/application.py
  naomi/mic.py
  naomi/profile.py
  plugins/speechhandler/shutdownplugin/shutdown.py
Labels: CLA: Signed, Priority: Low, Status: Completed, Status: Review Needed, Type: Enhancement

#148 Python3 warning for dev branch Readme
  README.md
Labels: Priority: High, Status: Review Needed, Type: Maintenance

#149 Variable type mismatch in Pico
  plugins/tts/pico-tts/pico.py
Labels: Priority: High, Status: Review Needed, Type: Bug

#154 Fix MaryTTS plugin
  plugins/tts/mary-tts/marytts.py
Labels: Priority: High, Status: Completed, Type: Bug

#157 Fix MaryTTS plugin
  plugins/tts/mary-tts/marytts.py
Labels: Priority: High, Status: Review Needed, Type: Bug

#153 Deepspeech model import
  plugins/stt/deepspeech-stt/deepspeechstt.py
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#159 imp module deprecated
  naomi/pluginstore.py
Labels: Priority: Low, Status: Completed, Status: Review Needed, Type: Maintenance
