Repository NaomiProject/Naomi, pull requests merged in 2019-10, with the labels that each got.

#213 Visualizations
  naomi/application.py
  naomi/commandline.py
  naomi/conversation.py
  naomi/plugin.py
  naomi/pluginstore.py
  naomi/visualizations.py
  plugins/audioengine/pyaudio-ae/pyaudioengine.py
  plugins/speechhandler/clock/clock.py
  plugins/speechhandler/shutdownplugin/shutdown.py
  plugins/speechhandler/wwis_weather/wwis_weather.py
  plugins/vad/snr_vad/snr_vad.py
  plugins/visualizations/terminal/__init__.py
  plugins/visualizations/terminal/plugin.info
  plugins/visualizations/terminal/terminal.py
  plugins/visualizations/terminal/test_terminal.py
Labels: Priority: Low, Status: Completed, Status: Review Needed, Type: Enhancement

#217 Added Issue: #124 - Adding lists for keywords
  naomi/application.py
  naomi/brain.py
  naomi/commandline.py
  naomi/conversation.py
  naomi/mic.py
  naomi/populate.py
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#220 Fixed settings
  naomi/commandline.py
  naomi/plugin.py
  naomi/testutils.py
  plugins/speechhandler/notifications/notifications.py
  plugins/speechhandler/wwis_weather/wwis_weather.py
  plugins/stt/att-stt/att.py
  plugins/stt/deepspeech-stt/deepspeechstt.py
  plugins/stt/google-stt/google.py
  plugins/stt/julius-stt/julius.py
  plugins/stt/kaldigstserver-stt/kaldigstserverplugin.py
  plugins/tti/adapt_tti/adapt_tti.py
  plugins/tti/padatious_tti/padatious_tti.py
  plugins/tts/google-tts/google.py
Labels: Priority: Critical, Status: Completed, Type: Bug

#221 Added encryption for email and password | Issue: #16
  Populate.py
  apt_requirements.txt
  naomi/populate.py
  naomi/profile.py
  naomi/run_command.py
  plugins/speechhandler/check_email/check_email.py
Labels: Priority: Medium, Status: Completed, Type: Enhancement

#222 Finished adding core variables as settings
  Populate.py
  naomi/app_utils.py
  naomi/application.py
  naomi/commandline.py
  naomi/mic.py
  naomi/populate.py
  naomi/visualizations.py
  plugins/speechhandler/check_email/check_email.py
  plugins/speechhandler/hackernews/hackernews.py
  plugins/speechhandler/news/news.py
  plugins/stt/pocketsphinx-stt/sphinxplugin.py
Labels: Priority: Critical, Status: Completed, Status: Review Needed, Type: Enhancement
