Repository NaomiProject/Naomi, pull requests merged in 2019-04, with the labels that each got.

#168 Naomi salutation
  naomi/conversation.py
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#170 Naobian Prep & Organization
  naomi/application.py
  naomi/paths.py
  naomi/plugin.py
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#171 Fixed several issues with populate
  naomi/application.py
  naomi/commandline.py
  naomi/populate.py
  naomi/profile.py
  plugins/tts/flite-tts/flite.py
Labels: Priority: High, Status: Completed, Status: Review Needed
