Repository NaomiProject/Naomi, pull requests merged in 2020-06, with the labels that each got.

#275 Further installer cleanup & features
  apt_requirements.txt
  installers/naomi-setup.sh
  installers/script.deb.sh
  msgfmt.py
  naomi-setup.sh
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Maintenance

#276 Deploy onliners via ftp
  .github/workflows/oneliners.yml
Labels: Status: Completed, Type: Enhancement

#277 Fixed parameter passing
  installers/script.deb.sh
  naomi-setup.sh
Labels: Priority: High, Status: Completed, Type: Bug

#278 Pocketsphinx python
  apt_requirements.txt
  installers/script.deb.sh
Labels: Priority: Medium, Status: On Hold, Type: Maintenance
