Repository NaomiProject/Naomi, pull requests merged in 2020-11, with the labels that each got.

#302 Updating Deb Install to Reflect New Nightly Builds
  installers/script.deb.sh
Labels: Priority: High, Status: Completed, Type: Bug

#304 SNR_VAD hearing
  plugins/vad/snr_vad/snr_vad.py
Labels: Priority: High, Status: Completed, Type: Bug

#297 Separate NPE into its own module
  naomi/__main__.py
  naomi/application.py
  naomi/npe.py
  naomi/pluginstore.py
Labels: Priority: Low, Status: Completed, Type: Maintenance

#300 Update Mozilla DeepSpeech
  apt_requirements.txt
  naomi/run_command.py
  plugins/stt/deepspeech-stt/deepspeechstt.py
  plugins/stt/pocketsphinx-stt/sphinxvocab.py
  plugins/tti/adapt_tti/adapt_tti.py
  plugins/tti/naomi_tti/naomi_tti.py
  plugins/tti/padatious_tti/padatious_tti.py
  python_requirements.txt
Labels: Priority: Medium, Status: Completed, Status: Review Needed, Type: Enhancement

#305 Fixed deepspeech model download
  naomi/app_utils.py
  plugins/stt/deepspeech-stt/deepspeechstt.py
Labels: Priority: High, Status: Completed, Type: Bug
