Repository NaomiProject/Naomi, pull requests merged in 2020-05, with the labels that each got.

#266 Allow Naomi to work with plugins with spaces in the names
  naomi/__main__.py
  naomi/application.py
  naomi/commandline.py
  naomi/mic.py
  plugins/speechhandler/mpdcontrol/mpdclient.py
Labels: Priority: Critical, Status: Completed, Type: Bug

#269 New NotificationClient plugin type
  NaomiSTTTrainer.py
  naomi/app_utils.py
  naomi/brain.py
  naomi/commandline.py
  naomi/notifier.py
  naomi/plugin.py
  naomi/pluginstore.py
  naomi/testutils.py
  plugins/notificationclient/respondtoemail/__init__.py
  plugins/notificationclient/respondtoemail/plugin.info
  plugins/notificationclient/respondtoemail/respondtoemail.py
  plugins/stt_trainer/pocketsphinx_adapt/pocketsphinx_adapt.py
  python_requirements.txt
Labels: Priority: Low, Status: Completed, Type: Enhancement

#274 New Naomi Setup Scripting & Some Cleanup
  Naomi.png
  README.md
  naomi-setup.sh
  naomi/__main__.py
  naomi/coloredformatting.py
  naomi/commandline.py
  naomi/populate.py
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Maintenance
