Repository NaomiProject/Naomi, pull requests merged in 2020-10, with the labels that each got.

#291 Abstracting Facebook plugins from Naomi source
  README.md
  plugins/speechhandler/birthday/__init__.py
  plugins/speechhandler/birthday/birthday.py
  plugins/speechhandler/birthday/locale/de-DE.po
  plugins/speechhandler/birthday/locale/en-US.po
  plugins/speechhandler/birthday/locale/fr-FR.po
  plugins/speechhandler/birthday/plugin.info
  plugins/speechhandler/notifications/__init__.py
  plugins/speechhandler/notifications/locale/de-DE.po
  plugins/speechhandler/notifications/locale/en-US.po
  plugins/speechhandler/notifications/locale/fr-FR.po
  plugins/speechhandler/notifications/notifications.py
  plugins/speechhandler/notifications/plugin.info
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#296 Add "knock knock" to default joke plugin templates
  .gitignore
  plugins/speechhandler/joke/joke.py
Labels: Priority: Low, Status: Completed, Type: Bug

#293 Naomi tti fix
  plugins/tti/naomi_tti/naomi_tti.py
Labels: Priority: High, Status: Completed, Type: Bug
