Repository NaomiProject/Naomi, pull requests merged in 2021-02, with the labels that each got.

#322 NPE plugins apt_requirements.txt file
  naomi/npe.py
Labels: Priority: High, Status: Completed, Type: Enhancement

#321 Remove python-pip apt package
  apt_requirements.txt
Labels: Priority: High, Status: Completed, Type: Maintenance

#320 Removing DeepSpeech from core
  apt_requirements.txt
  plugins/stt/deepspeech-stt/__init__.py
  plugins/stt/deepspeech-stt/deepspeechstt.py
  plugins/stt/deepspeech-stt/plugin.info
  python_requirements.txt
Labels: Status: Completed

#319 Ability to Force Update Naomi upon auto fail & Uninstall Naomi
  installers/naomi-setup.sh
  installers/script.deb.sh
  naomi-setup.sh
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#324 New Scripting
  README.md
  installers/naomi-setup.sh
  installers/script.deb.sh
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#328 Cleaning Up More Sudo
  installers/naomi-setup.sh
  installers/script.deb.sh
Labels: Priority: Critical, Status: Completed, Type: Bug

#327 Added options to Populate
  apt_requirements.txt
  naomi/application.py
  naomi/audioengine.py
  naomi/commandline.py
  naomi/pluginstore.py
  naomi/populate.py
  naomi/profile.py
Labels: Priority: Medium, Status: Completed, Type: Bug, Type: Enhancement
