Repository NaomiProject/Naomi, pull requests merged in 2024-02, with the labels that each got.

#396 Fix check_python_import()
  naomi/diagnose.py
Labels: Priority: Low, Status: Completed, Type: Bug

#398 Restore logging to screen
  naomi/__main__.py
  plugins/audioengine/pyaudio-ae/pyaudioengine.py
  plugins/speechhandler/shutdownplugin/shutdown.py
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#399 Remove default location from logfile
  naomi/__main__.py
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#394 Wit.ai STT Plugin update
  plugins/stt/witai-stt/plugin.info
  plugins/stt/witai-stt/witai.py
Labels: Priority: Low, Status: Completed, Type: Bug

#401 Fix Translations
  naomi/conversation.py
  naomi/data/locale/fr-FR.po
  naomi/plugin.py
Labels: Status: Completed, Priority: High, Type: Bug

#400 Witai stt update - French and German translations added
  plugins/stt/witai-stt/locale/de-DE.po
  plugins/stt/witai-stt/locale/en-US.po
  plugins/stt/witai-stt/locale/fr-FR.po
  plugins/stt/witai-stt/witai.py
Labels: Priority: Low, Status: Completed
