Repository NaomiProject/Naomi, pull requests merged in 2024-10, with the labels that each got.

#420 Remove padatious plugin from the Naomi repository
  plugins/tti/padatious_tti/__init__.py
  plugins/tti/padatious_tti/locale/de-DE.po
  plugins/tti/padatious_tti/locale/en-US.po
  plugins/tti/padatious_tti/locale/fr-FR.po
  plugins/tti/padatious_tti/padatious_tti.py
  plugins/tti/padatious_tti/plugin.info
  plugins/tti/padatious_tti/test_padatious_tti.py
Labels: Status: Review Needed, Status: Completed

#425 Fix typos
  CONTRIBUTING.md
  README.md
Labels: Priority: Low, Status: Completed, Type: Maintenance

#428 Changed audio to mono and 16MHz
  naomi/data/audio/beep_hi.wav
  naomi/data/audio/beep_lo.wav
Labels: Priority: Medium, Status: Completed, Type: Maintenance
